In [155]:
import pandas as pd

In [156]:
outlets = pd.read_csv("Data/QSR_outlet_dataset.csv")
socioeconomic = pd.read_csv('Data/QSR_socioeconomic_dataset.csv')

In [157]:
outlets.loc[outlets['Brand'].str.contains('five', case=False)].shape[0]

10

In [158]:
outlets.loc[outlets['Brand'].str.contains('five', case=False), 'Brand'] = "Five Guys"

In [159]:
outlets[outlets['Brand'].str.contains('five',case=False)]

,Outlet ID,Brand,Region,Province,Province_Shorthand,City,Menu_Category,Price_Range,Customer_Rating,Review_Count,Latitude,Longitude,Location_Type,Address,Source,Unnamed: 15
972,978,Five Guys,Piemonte,Torino,TO,Torino,Burgers,EUR 10-20,3.5,161,45.063273,7.678216,Transport Hub,Turin Porta Nuova 58 Corso Vittorio Emanuele I...,https://restaurants.fiveguys.it/en_it,NaN
973,979,Five Guys,Veneto,Venezia,VE,Venezia,Burgers,EUR 20-30,3.0,160,45.441756,12.321119,Transport Hub,Santa Lucia Station Fondamenta Santa Lucia bin...,https://restaurants.fiveguys.it/en_it,NaN
974,980,Five Guys,Lombardia,Milano,MI,Milano,Burgers,EUR 10-20,3.1,441,45.485427,9.205432,Transport Hub,"Milan Centrale Milano Centrale, Piazza Duca D'...",https://restaurants.fiveguys.it/en_it,NaN
975,981,Five Guys,Campania,Napoli,NaN,Napoli,Burgers,EUR 10-20,3.4,90,40.852010,14.270555,Transport Hub,"Naples Centrale Naples Centrale, Galleria Comm...",https://restaurants.fiveguys.it/en_it,NaN
976,982,Five Guys,Lazio,Roma,RM,Roma,Burgers,EUR 10-20,3.4,"1,135",41.901287,12.501576,Transport Hub,Rome Termini Piazzale dei Cinquencento 00187 Rome,https://restaurants.fiveguys.it/en_it,NaN
977,983,Five Guys,Toscana,Firenze,FI,Firenze,Burgers,EUR 10-20,3.3,319,43.776332,11.246787,Transport Hub,"Via Alamanni 2R Santa Maria Novella, Stazione ...",https://restaurants.fiveguys.it/en_it,NaN
978,984,Five Guys,Veneto,Vicenza,VI,Vicenza,Burgers,EUR 10-20,2.9,75,45.547967,11.584473,Shopping Mall,Via Aldo Moro Building 245 36100 Vicenza VI,https://restaurants.fiveguys.it/en_it,NaN
979,985,Five Guys,Lombardia,Milano,MI,Milano,Burgers,EUR 10-20,3.9,"1,735",45.466401,9.184342,City Center,Via Dante 7 20123 Milan,https://restaurants.fiveguys.it/en_it,NaN
980,986,Five Guys,Toscana,Firenze,FI,Campi Bisenzio,Burgers,EUR 20-30,3.2,162,43.848090,11.143273,Shopping Mall,Via San Quirico 165 50013 Campi Bisenzio Tuscany,https://restaurants.fiveguys.it/en_it,NaN
981,987,Five Guys,Lombardia,Milano,MI,Milano,Burgers,EUR 10-20,3.8,996,45.460171,9.181682,City Center,Via Stampa 13-15 Via Torino 20123 Milan Lombardy,https://restaurants.fiveguys.it/en_it,NaN

In [160]:
outlets.loc[outlets['Brand'].str.contains('popeyes', case=False)].shape[0]

15

In [161]:
outlets.loc[outlets['Brand'].str.contains('popeyes', case=False), 'Brand'] = 'Popeyes'

In [162]:
outlets[outlets['Brand'].str.contains('popeyes', case=False)]

,Outlet ID,Brand,Region,Province,Province_Shorthand,City,Menu_Category,Price_Range,Customer_Rating,Review_Count,Latitude,Longitude,Location_Type,Address,Source,Unnamed: 15
1135,1141,Popeyes,Lombardia,Milano,MI,Milano,Fried Chicken,EUR 10-20,4.3,603,45.458275,9.178189,City Center,"Via Edmondo de Amicis, 25, 20123 Milano MI",Google maps: popeyes locations in italy,NaN
1136,1142,Popeyes,Lombardia,Milano,MI,Milano,Fried Chicken,EUR 10-20,4.2,861,45.479616,9.209921,Commercial Area,"Corso Buenos Aires, 35, 20124 Milano MI",Google maps: popeyes locations in italy,NaN
1137,1143,Popeyes,Piemonte,Torino,TO,Torino,Fried Chicken,EUR 10-20,3.3,160,45.076763,7.670587,City Center,"Piazza Statuto, 16, 10122 Torino TO",Google maps: popeyes locations in italy,NaN
1138,1144,Popeyes,Abruzzo,Pescara,PE,Montesilvano,Fried Chicken,EUR 10-20,4.1,205,42.518628,14.146599,City Center,"Via Cavallotti, 3, 65015 Montesilvano PE",Google maps: popeyes locations in italy,NaN
1139,1145,Popeyes,Lombardia,Milano,MI,Milano,Fried Chicken,EUR 10-20,4.2,141,45.480537,9.192510,Commercial Area,"Piazzale Clotilde, Via Amerigo Vespucci, 20124...",Google maps: popeyes locations in italy,NaN
1140,1146,Popeyes,Lombardia,Milano,MI,Milano,Fried Chicken,EUR 10-20,4.1,92,45.477632,9.146370,Commercial Area,"Via Guglielmo Silva, 49, 20149 Milano MI",Google maps: popeyes locations in italy,NaN
1141,1147,Popeyes,Campania,Caserta,CE,Gricignano di Aversa,Fried Chicken,EUR 20-30,3.5,10,40.991575,14.251871,Shopping Mall,"81030 Gricignano di Aversa, Province of Caserta",Google maps: popeyes locations in italy,NaN
1142,1148,Popeyes,Lazio,Roma,RM,Roma,Fried Chicken,EUR 10-20,4.1,170,41.908276,12.538640,Commercial Area,"Via Tiburtina, 436, 00159 Roma RM",Google maps: popeyes locations in italy,NaN
1143,1149,Popeyes,Toscana,Firenze,FI,Firenze,Fried Chicken,EUR 10-20,3.8,36,43.784675,11.227741,Commercial Area,"Via Gaetano Donizetti, 16, 50144 Firenze FI",Google maps: popeyes locations in italy,NaN
1144,1150,Popeyes,Sicilia,Palermo,PA,Palermo,Fried Chicken,EUR 1-10,4.7,45,38.111723,13.335709,Commercial Area,"Via Libero Grassi, 38, 90135 Palermo PA",Google maps: popeyes locations in italy,NaN
1145,1151,Popeyes,Lombardia,Milano,MI,Milano,Fried Chicken,EUR 10-20,4.6,546,45.361051,9.216117,Shopping Mall,"Via Milano, 5, 20085 Milano MI",Google maps: popeyes locations in italy,NaN
1146,1152,Popeyes,Marche,Macerata,MC,Cingoli,Fried Chicken,EUR 10-20,4.4,"1,738",43.373650,13.153403,Service Area,"Località Castreccioni, 44, 62011 Cingoli MC",Google maps: popeyes locations in italy,NaN
1147,1153,Popeyes,Lazio,Roma,RM,Roma,Fried Chicken,EUR 1-10,4.6,"1,200",41.912692,12.454165,Residential Area,"Via della Giuliana, 53/55, 00195 Roma RM",Google maps: popeyes locations in italy,NaN
1148,1154,Popeyes,Marche,Macerata,MC,Potenza Picena,Fried Chicken,EUR 10-20,4.6,297,43.363585,13.618833,Residential Area,"Via delle Fonti, 11, 62018 Potenza Picena MC",Google maps: popeyes locations in italy,NaN
1149,1155,Popeyes,Emilia-Romagna,Bologna,BO,Imola,Fried Chicken,EUR 10-20,4.8,164,44.350597,11.715585,City Center,"Via Quaini, 43, 40026 Imola BO",Google maps: popeyes locations in italy,NaN

In [163]:
outlets.loc[outlets['Location_Type'].str.contains('transport hub -', case= False), 'Location_Type'] = "Transport Hub"

In [164]:
outlets[outlets['Location_Type'].str.contains('transport hub -', case=False)]

Empty DataFrame
Columns: [Outlet ID, Brand, Region, Province, Province_Shorthand, City, Menu_Category, Price_Range, Customer_Rating, Review_Count, Latitude, Longitude, Location_Type, Address, Source, Unnamed: 15]
Index: []

In [165]:
outlets.loc[outlets['Location_Type'].str.contains('Highway', case= False), 'Location_Type'] = 'Service Area'

In [166]:
outlets[outlets['Location_Type'].str.contains('highway', case= False)]

Empty DataFrame
Columns: [Outlet ID, Brand, Region, Province, Province_Shorthand, City, Menu_Category, Price_Range, Customer_Rating, Review_Count, Latitude, Longitude, Location_Type, Address, Source, Unnamed: 15]
Index: []

In [167]:
outlets.loc[outlets['Price_Range'].str.contains('EUR 1-60'), 'Price_Range'] = 'EUR 10-20'

In [168]:
outlets.loc[outlets['Price_Range'].str.contains('EUR 1-60')]

Empty DataFrame
Columns: [Outlet ID, Brand, Region, Province, Province_Shorthand, City, Menu_Category, Price_Range, Customer_Rating, Review_Count, Latitude, Longitude, Location_Type, Address, Source, Unnamed: 15]
Index: []

In [169]:
outlets.loc[outlets['Price_Range'].str.contains('EUR 1-20')]

,Outlet ID,Brand,Region,Province,Province_Shorthand,City,Menu_Category,Price_Range,Customer_Rating,Review_Count,Latitude,Longitude,Location_Type,Address,Source,Unnamed: 15
1127,1133,KFC,Lombardia,Milano,MI,Bellinzago Lombardo,Fried Chicken,EUR 1-20,3.5,31,45.545844,9.453550,Shopping Mall,Via Padana Superiore 154 20060 Bellinzago Lomb...,https://www.kfc.it/ristoranti,NaN
1249,1256,Alice Pizza,Veneto,Venezia,VE,Venezia,Pizza,EUR 1-20,4.0,465,45.510153,12.227264,Shopping Mall,Alice Mestre Via Don Tosatto 22 041-8760064,https://www.alicepizza.it/en/pizzerias/,NaN
1375,1383,Alice Pizza,Toscana,Siena,SI,Siena,Pizza,EUR 1-20,3.7,41,43.330620,11.323072,Transport Hub,"Alice PortaSiena Galleria PortaSiena, Piazzale...",https://www.alicepizza.it/en/pizzerias/,NaN
1722,1731,La Piadineria,Lazio,Roma,RM,Roma,Piadine,EUR 1-20,4.0,137,41.816944,12.459648,Shopping Mall,Roma C.C. Euroma Roma (RM) Viale Dell'Oceano P...,https://lapiadineria.com/i-nostri-ristoranti-r...,NaN
1761,1770,La Piadineria,Lombardia,Milano,MI,Paderno Dugnano,Piadine,EUR 1-20,4.1,263,45.574630,9.179773,Shopping Mall,Paderno Dugnano C.C. Brianza Paderno Dugnano (...,https://lapiadineria.com/i-nostri-ristoranti-r...,NaN
1936,1945,La Piadineria,Lombardia,Monza e della Brianza,MB,Lissone,Piadine,EUR 1-20,3.7,291,45.602847,9.251325,Commercial Area,Lissone Lissone (MB) Via Triest 37,https://lapiadineria.com/i-nostri-ristoranti-r...,NaN
1977,1986,La Piadineria,Abruzzo,Chieti,CH,Zona Industriale Val Pescara,Piadine,EUR 1-20,4.2,66,42.415418,14.168469,Shopping Mall,Centro d'Abruzzo San Giovanni Teatino (CH) Via Po,https://lapiadineria.com/i-nostri-ristoranti-r...,NaN
1991,2000,La Piadineria,Lazio,Roma,RM,Roma,Piadine,EUR 1-20,4.0,137,41.816944,12.459648,Shopping Mall,Roma C.C. Euroma - fronte Ipercoop Roma (RM) V...,https://lapiadineria.com/i-nostri-ristoranti-r...,NaN
2027,2037,La Piadineria,Lazio,Roma,RM,Roma,Piadine,EUR 1-20,3.8,68,41.881586,12.566472,Commercial Area,Roma - P.zza Dei Mirti Roma (RM) Piazza dei Mi...,https://lapiadineria.com/i-nostri-ristoranti-r...,NaN
2028,2038,La Piadineria,Lazio,Roma,RM,Roma,Piadine,EUR 1-20,3.3,25,41.933522,12.512555,Residential Area,Roma P.zza Vescovio Roma (RM) P.zza Vescovio,https://lapiadineria.com/i-nostri-ristoranti-r...,NaN
2106,2116,La Piadineria,Veneto,Treviso,TV,Conegliano,Piadine,EUR 1-20,4.1,61,45.878554,12.315102,Shopping Mall,Conegliano - Centro Commerciale Conè Coneglian...,https://lapiadineria.com/i-nostri-ristoranti-r...,NaN
2108,2118,La Piadineria,Marche,Ascoli Piceno,AP,San Benedetto del Tronto,Piadine,EUR 1-20,4.5,36,42.899117,13.892842,Shopping Mall,San Benedetto Del Tronto - Centro Commerciale ...,https://lapiadineria.com/i-nostri-ristoranti-r...,NaN
2114,2124,La Piadineria,Emilia-Romagna,Forlì-Cesena,FC,Forlì,Piadine,EUR 1-20,4.0,73,44.243164,12.082272,Shopping Mall,Forlì - Centro Commerciale Punta di Ferro Forl...,https://lapiadineria.com/i-nostri-ristoranti-r...,NaN
2147,2157,La Piadineria,Campania,Napoli,NaN,Napoli,Piadine,EUR 1-20,4.5,35,40.842582,14.233476,Transport Hub,Napoli - Piazza Fuga Napoli (NA) Piazza fuga 1...,https://lapiadineria.com/i-nostri-ristoranti-r...,NaN
2153,2163,La Piadineria,Sicilia,Catania,CT,Catania,Piadine,EUR 1-20,4.6,25,37.504898,15.086477,City Center,Catania San Giuliano Catania (CT) Via Sangiuli...,https://lapiadineria.com/i-nostri-ristoranti-r...,NaN
2599,2610,Autogrill,Veneto,Venezia,VE,Venezia,Bar/Café,EUR 1-20,2.7,33,45.525773,12.262858,Service Area,"Bazzera Sud, A4 Torino - Trieste, 30174 Verona...",https://www.autogrill.it/wp-content/uploads/20...,NaN
2789,2801,Autogrill,Lombardia,Bergamo,BG,Seriate,Bar/Café,EUR 1-20,3.5,33,45.677853,9.706622,Service Area,"Seriate Oil, SS671, km 8,9, 24068 Seriate BG, ...",https://www.autogrill.it/wp-content/uploads/20...,NaN

In [170]:
outlets.loc[outlets['Outlet ID'] == 1256, 'Price_Range'] = 'EUR 1-10'
outlets.loc[outlets['Outlet ID'] == 1770, 'Price_Range'] = 'EUR 10-20'
outlets.loc[outlets['Outlet ID'] == 1945, 'Price_Range'] = 'EUR 10-20'
outlets.loc[outlets['Outlet ID'] == 2037, 'Price_Range'] = 'EUR 1-10'
outlets.loc[outlets['Outlet ID'] == 2116, 'Price_Range'] = 'EUR 1-10'
outlets.loc[outlets['Outlet ID'] == 2118, 'Price_Range'] = 'EUR 1-10'
outlets.loc[outlets['Outlet ID'] == 2157, 'Price_Range'] = 'EUR 10-20'
outlets.loc[outlets['Outlet ID'] == 2163, 'Price_Range'] = 'EUR 10-20'
outlets.loc[outlets['Outlet ID'] == 2610, 'Price_Range'] = 'EUR 10-20'

In [171]:
outlets.loc[outlets['Outlet ID'] == 2116]

,Outlet ID,Brand,Region,Province,Province_Shorthand,City,Menu_Category,Price_Range,Customer_Rating,Review_Count,Latitude,Longitude,Location_Type,Address,Source,Unnamed: 15
2106,2116,La Piadineria,Veneto,Treviso,TV,Conegliano,Piadine,EUR 1-10,4.1,61,45.878554,12.315102,Shopping Mall,Conegliano - Centro Commerciale Conè Coneglian...,https://lapiadineria.com/i-nostri-ristoranti-r...,NaN

In [172]:
outlets.loc[outlets['Price_Range'] == 'EUR 10-30']

,Outlet ID,Brand,Region,Province,Province_Shorthand,City,Menu_Category,Price_Range,Customer_Rating,Review_Count,Latitude,Longitude,Location_Type,Address,Source,Unnamed: 15
1457,1465,Old Wild West,Lazio,Latina,LT,Latina,Burgers,EUR 10-30,4.1,"3,322",41.479335,12.869871,Commercial Area,Latina Via Piave Via Piave km 67.700 - 04100 L...,https://www.oldwildwest.it/en/restaurants,NaN
1568,1576,Old Wild West,Sardegna,Cagliari,CA,Cagliari,Burgers,EUR 10-30,4.1,"2,508",39.226562,9.098228,Commercial Area,Cagliari Unione Sarda Piazza Unione Sarda - 09...,https://www.oldwildwest.it/en/restaurants,NaN
1609,1617,Old Wild West,Veneto,Treviso,TV,Caerano di San Marco,Burgers,EUR 10-30,3.6,109,45.785644,11.994592,Commercial Area,Via Padova 1 - Caerano di San Marco (TV),https://www.oldwildwest.it/en/restaurants,NaN
2260,2271,Roadhouse Restaurant,Lombardia,Milano,MI,Arese,Steakhouse,EUR 10-30,3.6,"1,685",45.563930,9.054745,Shopping Mall,"Via Giuseppe Eugenio Luraghi, 11, 20044 Arese ...",https://www.roadhouse.it/store-locator/#!,NaN
2314,2325,Roadhouse Restaurant,Lazio,Roma,RM,Roma,Steakhouse,EUR 10-30,3.8,990,41.884336,12.606671,Shopping Mall,"V.le Marisa Bellisario, 00155 Roma RM, Italy",https://www.roadhouse.it/store-locator/#!,NaN
2378,2389,Roadhouse Restaurant,Trentino-Alto Adige,Trento,TN,Rovereto,Steakhouse,EUR 10-30,3.8,"1,138",45.873131,11.030960,Commercial Area,"Via dell'Abetone, 53, 38068 Rovereto TN, Italy",https://www.roadhouse.it/store-locator/#!,NaN

In [173]:
outlets.loc[outlets['Outlet ID'] == 1465, 'Price_Range'] = 'EUR 20-30'
outlets.loc[outlets['Outlet ID'] == 1576, 'Price_Range'] = 'EUR 20-30'
outlets.loc[outlets['Outlet ID'] == 1617, 'Price_Range'] = 'EUR 10-20'
outlets.loc[outlets['Outlet ID'] == 2325, 'Price_Range'] = 'EUR 20-30'
outlets.loc[outlets['Outlet ID'] == 2389, 'Price_Range'] = 'EUR 10-20'

In [174]:
outlets.loc[outlets['Outlet ID'] == 2389, 'Price_Range']

2378    EUR 10-20
Name: Price_Range, dtype: str

In [175]:
outlets.info()

<class 'pandas.DataFrame'>
RangeIndex: 2858 entries, 0 to 2857
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Outlet ID           2858 non-null   int64
 1   Brand               2858 non-null   str
 2   Region              2858 non-null   str
 3   Province            2858 non-null   str
 4   Province_Shorthand  2790 non-null   str
 5   City                2858 non-null   str
 6   Menu_Category       2858 non-null   str
 7   Price_Range         2793 non-null   str
 8   Customer_Rating     2858 non-null   float64
 9   Review_Count        2858 non-null   str
 10  Latitude            2858 non-null   float64
 11  Longitude           2858 non-null   float64
 12  Location_Type       2858 non-null   str
 13  Address             2858 non-null   str
 14  Source              2858 non-null   str
 15  Unnamed: 15         0 non-null      float64
dtypes: float64(4), int64(1), str(11)
memory usage: 357.4 KB

In [176]:
outlets['Review_Count'] = outlets['Review_Count'].astype(str).str.replace(",", "", regex= False).astype(int)

In [177]:
socioeconomic.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Region                        20 non-null     str
 1   Province_Count                20 non-null     int64
 2   Region_Area                   20 non-null     str
 3   Population                    20 non-null     int64
 4   Population Density            20 non-null     float64
 5   Disposable Income per capita  20 non-null     str
 6   Total Tourism Flow            20 non-null     str
 7   Foreign Tourism Flow          20 non-null     str
 8   Median Income                 20 non-null     str
dtypes: float64(1), int64(2), str(6)
memory usage: 1.5 KB

In [178]:
socioeconomic['Region_Area'] = socioeconomic['Region_Area'].str.replace(",", "", regex= False).astype(float)
socioeconomic['Disposable Income per capita'] = socioeconomic['Disposable Income per capita'].str.replace(",", "", regex= False).astype(int)
socioeconomic['Total Tourism Flow'] = socioeconomic['Total Tourism Flow'].str.replace(',','',regex=False).astype(float)
socioeconomic['Foreign Tourism Flow'] = socioeconomic['Foreign Tourism Flow'].str.replace(',','',regex=False).astype(float)
socioeconomic['Median Income'] = socioeconomic['Median Income'].str.replace(',','',regex= False).astype(int)

In [179]:
socioeconomic.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Region                        20 non-null     str
 1   Province_Count                20 non-null     int64
 2   Region_Area                   20 non-null     float64
 3   Population                    20 non-null     int64
 4   Population Density            20 non-null     float64
 5   Disposable Income per capita  20 non-null     int64
 6   Total Tourism Flow            20 non-null     float64
 7   Foreign Tourism Flow          20 non-null     float64
 8   Median Income                 20 non-null     int64
dtypes: float64(4), int64(4), str(1)
memory usage: 1.5 KB

In [180]:
duplicate_coordinate_rows = outlets[
    outlets.duplicated(
        subset=["Latitude", "Longitude"],
        keep=False
    )
].sort_values(["Latitude", "Longitude"])

#To display all the results in a scrolldown option
from IPython.display import display, HTML

html_table = duplicate_coordinate_rows.loc[:, ['Outlet ID', 'Brand', 'City', 'Customer_Rating','Review_Count', 'Latitude', 'Longitude', 'Address']].to_html(index=False)

display(HTML(f"""
<div style="
    max-height: 300px;
    overflow-y: auto;
    overflow-x: auto;
    border: 1px solid #555;
    padding: 8px;
">
{html_table}
</div>
"""))

In [181]:
outlets.to_csv("Data/QSR_outlet_dataset_to_clean.csv", index=False)
socioeconomic.to_csv("Data/QSR_socioeconomic_dataset_cleaned.csv", index=False)

In [182]:
cleaned_outlets = pd.read_csv("Data/QSR_outlet_dataset_cleaned.csv")

In [183]:
duplicate_coordinate_rows = cleaned_outlets[
    cleaned_outlets.duplicated(
        subset=["Latitude", "Longitude"],
        keep=False
    )
].sort_values(["Latitude", "Longitude"])

#To display all the results in a scrolldown option
from IPython.display import display, HTML

html_table = duplicate_coordinate_rows.loc[:, ['Outlet ID', 'Brand', 'City', 'Customer_Rating','Review_Count', 'Latitude', 'Longitude', 'Address']].to_html(index=False)

display(HTML(f"""
<div style="
    max-height: 300px;
    overflow-y: auto;
    overflow-x: auto;
    border: 1px solid #555;
    padding: 8px;
">
{html_table}
</div>
"""))

In [184]:
#By brand, address and city

duplicate_coordinate_rows = cleaned_outlets[
    cleaned_outlets.duplicated(
        subset=["Brand", "City", "Address"],
        keep=False
    )
].sort_values(["Brand"])

#To display all the results in a scrolldown option
from IPython.display import display, HTML

html_table = duplicate_coordinate_rows.loc[:, ['Outlet ID', 'Brand', 'City', 'Customer_Rating','Review_Count', 'Latitude', 'Longitude', 'Address']].to_html(index=False)

display(HTML(f"""
<div style="
    max-height: 300px;
    overflow-y: auto;
    overflow-x: auto;
    border: 1px solid #555;
    padding: 8px;
">
{html_table}
</div>
"""))